import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { spawnSync } from 'node:child_process';

import { describe, expect, test } from 'vitest';

const repoRoot = resolve(__dirname, '..', '..');
const scriptPath = join(repoRoot, 'apps', 'desktop', 'scripts', 'inject-relay-token.cjs');
const committedBuildPath = join(repoRoot, 'apps', 'desktop', 'src', 'pairing-build.ts');

describe('desktop relay build injector', () => {
  test('packaged builds without injected relay secrets do not fall back to the dev relay token', () => {
    const source = readFileSync(join(repoRoot, 'apps', 'desktop', 'src', 'pairing-ipc.ts'), 'utf8');

    expect(source).not.toContain("'dev-pairing-token'");
    expect(source).not.toContain('scouting-assistant.up.railway.app');
    expect(source).toContain(
      "const DEFAULT_RELAY_URL = (process.env.PAIRING_RELAY_URL || BUILT_IN_RELAY_URL).trim();",
    );
    expect(source).toContain(
      "const DEFAULT_RELAY_TOKEN = (process.env.PAIRING_TOKEN || BUILT_IN_RELAY_TOKEN).trim();",
    );
  });

  test('writes baked relay URL and token to the requested output file', () => {
    const original = readFileSync(committedBuildPath, 'utf8');
    const dir = mkdtempSync(join(tmpdir(), 'cardmirror-relay-build-'));
    const out = join(dir, 'pairing-build.ts');
    try {
      const result = spawnSync(process.execPath, [scriptPath], {
        cwd: repoRoot,
        env: {
          ...process.env,
          PAIRING_TOKEN: 'private-token',
          PAIRING_RELAY_URL: 'https://relay.example.test/relay',
          PAIRING_BUILD_OUT: out,
        },
        encoding: 'utf8',
      });

      expect(result.status, result.stderr || result.stdout).toBe(0);
      expect(readFileSync(out, 'utf8')).toBe(
        '// AUTO-GENERATED by scripts/inject-relay-token.cjs - do not edit.\n' +
          'export const BUILT_IN_RELAY_URL = "https://relay.example.test/relay";\n' +
          'export const BUILT_IN_RELAY_TOKEN = "private-token";\n',
      );
    } finally {
      writeFileSync(committedBuildPath, original);
      rmSync(dir, { recursive: true, force: true });
    }
  });

  test('trims pasted relay secrets before baking them into an installer', () => {
    const original = readFileSync(committedBuildPath, 'utf8');
    const dir = mkdtempSync(join(tmpdir(), 'cardmirror-relay-build-'));
    const out = join(dir, 'pairing-build.ts');
    try {
      const result = spawnSync(process.execPath, [scriptPath], {
        cwd: repoRoot,
        env: {
          ...process.env,
          PAIRING_TOKEN: '  private-token\r\n',
          PAIRING_RELAY_URL: '  https://relay.example.test/relay/  ',
          PAIRING_BUILD_OUT: out,
        },
        encoding: 'utf8',
      });

      expect(result.status, result.stderr || result.stdout).toBe(0);
      expect(readFileSync(out, 'utf8')).toBe(
        '// AUTO-GENERATED by scripts/inject-relay-token.cjs - do not edit.\n' +
          'export const BUILT_IN_RELAY_URL = "https://relay.example.test/relay";\n' +
          'export const BUILT_IN_RELAY_TOKEN = "private-token";\n',
      );
    } finally {
      writeFileSync(committedBuildPath, original);
      rmSync(dir, { recursive: true, force: true });
    }
  });

  test('desktop package builds bake relay defaults before packaging', () => {
    const pkg = JSON.parse(
      readFileSync(join(repoRoot, 'apps', 'desktop', 'package.json'), 'utf8'),
    ) as { scripts: Record<string, string> };

    expect(pkg.scripts['bake:relay']).toBe('node scripts/inject-relay-token.cjs');
    expect(pkg.scripts['pack']).toContain('npm run bake:relay &&');
    expect(pkg.scripts['dist']).toContain('npm run bake:relay &&');
    expect(pkg.scripts['release']).toContain('npm run bake:relay &&');
  });
});
